function root1 = R1_optimized(x,y)
%R1_OPTIMIZED
%    ROOT1 = R1_OPTIMIZED(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Sep-2020 02:45:07

t2 = x.^2;
t3 = y.^2;
t4 = t2.*1.358565418461899e+2;
t5 = t3.*1.358565418461899e+2;
t6 = -t4;
t7 = -t5;
t8 = t4+t5-7.813712585965211;
t9 = t8.^2;
t10 = t9+3.268274071930727e-2;
t11 = sqrt(t10);
t12 = t6+t7+t11+7.813712585965211;
root1 = 1.0./t12.^(1.0./3.0).*(-3.197222222222222e-1)+t12.^(1.0./3.0)+7.0./6.0e+1;
